name: Tests
on: [ push ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run tests
        run: |
          yarn
          yarn test
